# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
 keywords =
  [
      "Absolute",
      "Absolute Convergence",
      "Absolute Maximum",
      "Absolute Minimum",
      "Absolute Value",
      "Absolutely Convergent",
      "Acceleration",
      "Algorithm",
      "Alternating Series",
      "Alternating Series Estimation Theorem",
      "Alternating Series Remainder",
      "Alternating Series Test",
      "Analytic Methods",
      "Annulus",
      "Antiderivative of a Function",
      "Antidifferentiation",
      "Approximation by Differentials",
      "Arc",
      "Arc Length of a Curve",
      "Arccosine",
      "Arcsine",
      "Arctangent",
      "Area",
      "Area under Velocity Function",
      "Area between Curves",
      "Area of an Ellipse",
      "Area under a Curve",
      "Area Using Parametric Equations",
      "Area Using Polar Coordinates",
      "Asymptote",
      "Autonomous",
      "Average Rate of Change",
      "Average Value of a Function",
      "Average Velocity",
      "Axis of Rotation",
      "Boundary Value Problem",
      "Bounded Function",
      "Bounded Sequence",
      "Bounds of Integration",
      "Calculus",
      "Carrying Capacity",
      "Cartesian Form",
      "Cavalieri’s Principle",
      "Center of Mass Formula",
      "central difference",
      "Centroid",
      "Chain Rule",
      "Codomain",
      "Common Ratio",
      "Comparison Test",
      "Composition",
      "Concave",
      "Concave Down",
      "Concave Up",
      "Concavity",
      "Conditional Convergence",
      "Constant Function",
      "Constant Multiple Rule for Definite Integral",
      "Constant Term",
      "Continued Sum",
      "Continuous",
      "Continuous at x = a",
      "Continuous Function",
      "Continuously Differentiable Function",
      "Converge",
      "Converge Absolutely",
      "Converge Conditionally",
      "Convergence",
      "Convergence Tests",
      "Convergent Sequence",
      "Convergent Series",
      "Cosecant",
      "Cosine",
      "Cotangent",
      "Critical Number",
      "Critical Point",
      "Critical Value",
      "Curly d",
      "Curve",
      "Curve Sketching",
      "Cusp",
      "Cylindrical Shell Method",
      "Decreasing Function",
      "Definite Integral",
      "Definite Integral Rules",
      "Definition",
      "Definition of Definite Integral",
      "Degenerate",
      "Del Operator",
      "Deleted Neighborhood",
      "Delta (Δ δ)",
      "Density",
      "Derivative",
      "Derivative of a Power Series",
      "Derivative Rules",
      "Difference Quotient",
      "Differentiable",
      "Differential",
      "Differential Equation",
      "Differentiation",
      "Differentiation Rules",
      "Discontinuity",
      "Discontinuous Function",
      "Disk",
      "Disk Method",
      "Distance from a Point to a Line",
      "Distance Traveled",
      "Diverge",
      "Divergence Test",
      "Divergent Sequence",
      "Divergent Series",
      "Domain",
      "e",
      "Ellipsoid",
      "End Behavior",
      "Epsilon (Ε ε)",
      "Equation",
      "Equilibrium Solution",
      "Error Function",
      "Essential Discontinuity",
      "Euler’s Method",
      "Evaluate",
      "Explicit Differentiation",
      "Explicit Function",
      "Exponential Decay",
      "Exponential Function",
      "Exponential Growth",
      "Exponential Model",
      "Extreme Value",
      "Extreme Value Theorem",
      "Extreme Values of a Polynomial",
      "Extremum",
      "Factorial",
      "Falling Bodies",
      "Fibonacci sequence",
      "First Derivative",
      "First Derivative Test",
      "First Order",
      "First Order Differential Equation",
      "Fixed",
      "Foot-Pound",
      "Forward Difference",
      "Function",
      "Function Operations",
      "Function-Derivative Pair",
      "Fundamental Theorem of Calculus",
      "Fundamental Trigonometric Identity",
      "General Antiderivative",
      "Geometric",
      "Geometric Series",
      "Geometric Sum",
      "Greatest Lower Bound",
      "Global",
      "Global Maximum",
      "Global Minimum",
      "Golden Spiral",
      "Graph",
      "Graph of Derivative",
      "Graph of Antiderivative",
      "Graphic Methods",
      "Greatest Lower Bound",
      "Greek Alphabet",
      "Harmonic Progression",
      "Harmonic Sequence",
      "Harmonic Series",
      "Helix",
      "Higher Derivative",
      "Hole",
      "Homogeneous System of Equations",
      "Hooke’s Law",
      "Horizontal Asymptote",
      "Hyperbolic Trigonometry",
      "Identity Function",
      "Implicit Differentiation",
      "Implicit Function or Relation",
      "Improper Integral",
      "Increasing",
      "Increasing Function",
      "Indefinite Integral",
      "Indefinite Integral Rules",
      "Indeterminate",
      "Indeterminate Difference",
      "Indeterminate Form",
      "Indeterminate Power",
      "Indeterminate Product",
      "Infinite Geometric Series",
      "Infinite Limit",
      "Infinite Series",
      "Infinitesimal",
      "Infinity",
      "Inflection Point",
      "Initial Condition",
      "Initial Value Problem",
      "Instantaneous Acceleration",
      "Instantaneous Rate of Change",
      "Instantaneous Velocity",
      "Integrable Function",
      "Integral",
      "Integral Function",
      "Integral Methods",
      "Integral of a Function",
      "Integral of a Power Series",
      "Integral Rules",
      "Integral Sign",
      "Integral Table",
      "Integral Test",
      "Integral Test Remainder",
      "Integrand",
      "Integration",
      "Integration by Parts",
      "Integration by Substitution",
      "Integration Methods",
      "Intermediate Value Theorem",
      "Interval of Convergence",
      "Iterative Process",
      "Initial Value Problem",
      "Jump Discontinuity",
      "L'Hôpital's Rule",
      "Lagrange Error Bound",
      "Least Upper Bound",
      "Left Limit",
      "Lemniscate",
      "Limit",
      "Limit Comparison Test",
      "Limit from Above",
      "Limit from Below",
      "Limit from the Left",
      "Limit from the Right",
      "Limit Involving Infinity",
      "Limit Test for Divergence",
      "Limits of Integration",
      "Local",
      "Local Behavior",
      "Local Linearization",
      "Local Maximum",
      "Local Minimum",
      "Locally Linear",
      "Logarithm",
      "Logarithmic Differentiation",
      "Logistic",
      "Logistic Equation",
      "Logistic Growth",
      "Maclaurin Series",
      "Mass",
      "Mathematical Model",
      "Maximize",
      "Maximum	(verbs vs nouns",
      "Maximum of a Function",
      "Mean Value Theorem",
      "Mean Value Theorem for Integrals",
      "Mesh",
      "Midpoint Rule",
      "Min/Max Theorem",
      "Minimize",
      "Minimum of a Function",
      "Mode",
      "Model",
      "Moment",
      "Multivariable",
      "Multivariable Analysis",
      "Multivariable Calculus",
      "Multivariate",
      "n Tuple",
      "Neighborhood",
      "Net Signed Area",
      "Newton-meter",
      "Newton's Method",
      "Newton’s Law of Cooling",
      "Norm of a Partition",
      "Normal",
      "nth Degree Taylor Polynomial",
      "nth Derivative",
      "nth Partial Sum",
      "Oblate Spheroid",
      "One Sided Limit",
      "One-Sided",
      "One-to-One",
      "Operations on Functions",
      "Order of a Differential Equation",
      "Ordinary Differential Equation",
      "Orthogonal",
      "p Series",
      "Parallel Cross Sections",
      "Parameter (Algebra)",
      "Parametric Derivative Formulas",
      "Parametric Equations",
      "Parametric Integral Formula",
      "Parametrize",
      "Partial Fractions",
      "Partial Sum",
      "Partial Sum of a Series",
      "Partition of an Interval",
      "Per Capita Growth Rate",
      "Piecewise Continuous Function",
      "Pinching Theorem",
      "Polar Derivative Formulas",
      "Polar Integral Formula",
      "Position",
      "Positive Series",
      "Power Function",
      "Power Rule",
      "Power Series",
      "Power Series Convergence",
      "Product Rule",
      "Projectile Motion",
      "Prolate Spheroid",
      "Quotient Rule",
      "Radius of Convergence",
      "Ratio Test",
      "Rationalizing Substitutions",
      "Reciprocal Rule",
      "Rectangular Form",
      "Related Rates",
      "Relative",
      "Relative Maximum",
      "Relative Minimum",
      "Remainder of a Series",
      "Removable Discontinuity",
      "Riemann Sum",
      "Right Limit",
      "Rolle's Theorem",
      "Root Test",
      "Scalar",
      "Secant",
      "Secant Line",
      "Second Derivative",
      "Second Derivative Test",
      "Second Order Critical Point",
      "Second Order Differential Equation",
      "Separable",
      "Separable Differential Equation",
      "Sequence",
      "Sequence of Partial Sums",
      "Series",
      "Series Rules",
      "Shell Method",
      "Sigma (Σ σ)",
      "Sigma Notation",
      "Simple Closed Curve",
      "Simple Harmonic Motion (SHM)",
      "Simpson’s rule",
      "Sine",
      "Slope",
      "Slope Field",
      "Slope of a Curve",
      "Solid",
      "Solid of Revolution",
      "Solution",
      "Solve Analytically",
      "Solve Graphically",
      "Speed",
      "Square Root",
      "Squeeze (or Sandwich) Theorem",
      "Stable",
      "Step Discontinuity",
      "Substitution Method",
      "Sum Rule",
      "Sum Rule for Definite Integral",
      "Surface",
      "Surface Area of a Surface of Revolution",
      "Surface of Revolution",
      "Table of Integrals",
      "Tangent",
      "Tangent Line",
      "Taylor Polynomial",
      "Taylor Series",
      "Taylor Series Remainder",
      "Term",
      "Theorem of Pappus",
      "Torus",
      "Total Change Theorem",
      "Trapezoid Rule",
      "Triangular Numbers",
      "Trig Substitution",
      "Trigonometry",
      "u Substitution",
      "Unbounded Integrand",
      "Unbounded Region of Integration",
      "Uniform",
      "Unstable",
      "Vector",
      "Vector Derivative",
      "Vector Calculus",
      "Velocity",
      "Vertical Asymptote",
      "Volume",
      "Volume by Parallel Cross Sections",
      "Washer",
      "Washer Method",
      "Weighted Average",
      "Work",
      "Word Problems"
  ]

  keywords.each do |keyword|
    Keyword.create!({name:keyword})
  end


professors = [
    "Allen,Angela",
    "Anshelevich,Michael",
    "Aurispa,Benjamin",
    "Austin,Amy",
    "Baskin,Dean",
    "Battle,Guy",
    "Baudier,Florent",
    "Berkolaiko,Gregory",
    "Boas,Harold",
    "Bollinger,Kathryn",
    "Bonito,Andrea",
    "Brannan,Michael",
    "Carter,Tamara",
    "Chen,Goong",
    "Chung,Eric",
    "Coffelt,Vanessa",
    "Comech,Andrew",
    "Daripa,Prabir",
    "Demlow,Alan",
    "DeVore,Ronald",
    "Dykema,Ken",
    "Efendiev,Yalchin",
    "Epstein,Janice",
    "Erdélyi,Tamás",
    "Foucart,Simon",
    "Fulling,Stephen",
    "Grigorchuk,Rostislav",
    "Guermond,Jean-Luc",
    "Gustafson,Robert",
    "Hanin,Boris",
    "Hester,Yvette",
    "Holmes,Irina",
    "Howard,Peter",
    "Howe,Roger",
    "Johnson,Bill",
    "Johnson,Maya",
    "Jung,Junehyuk",
    "Kahlig,Joe",
    "Kerr,David",
    "Kilmer,Kendra",
    "Kim,Joungdong",
    "Kuan,Jeffrey",
    "Kuchment,Peter",
    "LahodnyJr,Glenn",
    "Landsberg,Joseph",
    "Larson,David",
    "Lazarov,Raytcho",
    "Lee,SangRae",
    "Lewis,Jennifer",
    "Lima-Filho,Paulo",
    "Liu,Chun-Hung",
    "Lynch,Benjamin",
    "Maier,Matthias",
    "Manuel,David",
    "Masri,Riad",
    "Matusevich,LauraFelicia",
    "Narcowich,Francis",
    "Nekrashevych,Volodymyr",
    "Onica,Constantin",
    "Orchard,Patrick",
    "Panetta,Lee",
    "Paouris,Grigoris",
    "Papanikolas,Matthew",
    "Pasciak,Joe",
    "Pearlstein,Gregory",
    "Pearlstein,Rosanna",
    "Petrova,Guergana",
    "Pisier,Gilles",
    "Poltoratski,Alexei",
    "Popov,Bojan",
    "Procaccia,Eviatar",
    "Rahm,Robert",
    "Rajagopal,Kumbakonam",
    "Ramsey,Heather",
    "Reddy,J.N.",
    "Reihani,Kamran",
    "Rojas,J.Maurice",
    "Roque-Sol,Marco",
    "Rowell,Eric",
    "Rundell,William",
    "Schielack,Vince",
    "Schlumprecht,Thomas",
    "Schrader,Todd",
    "Sengupta,Sinjini",
    "Shatalov,Oksana",
    "Shiu,Anne",
    "Sivakumar,N.",
    "Slattery,John",
    "Smith,Roger",
    "Sottile,Frank",
    "Stiller,Peter",
    "Straube,Emil",
    "Taliaferro,Steven",
    "Titi,Edriss",
    "Tretkoff,Marvin",
    "Tucker-Drob,Robin",
    "Vorobets,Mariya",
    "Vorobets,Yaroslav",
    "Ward,Joe",
    "Whitfield,Jennifer",
    "Wilkerson,Clarence",
    "Witherspoon,Sarah",
    "Xie,Zhizhang",
    "Yan,Catherine",
    "Yang,Tian",
    "Yasskin,Philip",
    "Young,Matthew",
    "Yu,Guoliang",
    "Zelenko,Igor",
    "Zhou,Jianxin",
    "Cai,Yue",
    "Cao,Xiaomin",
    "Faller,Hugues",
    "Gao,Li",
    "Goswami,Souvik",
    "Guignard,Diane",
    "Guo,Hao",
    "Guo,Senlin",
    "Harper,Alicia",
    "Jantsch,Peter",
    "Ji,Shaochun",
    "Liu,Xin",
    "Lynch,Richard",
    "Nite,Sandra",
    "Sergeev,Alexey",
    "Shi,Shuhui",
    "Tang,Xiaoxian",
    "Ventura,Emanuele",
    "Volcic,Jurij",
    "Wang,Jiao",
    "Wei,Chunqiu",
    "Yang,Yong",
    "Yu,Shilin",
    "Zhao,Jia",
    "Allen,G.Donald",
    "Barrow,David",
    "Belmonte,Art",
    "Boggess,Al",
    "Borosh,Itshak",
    "Bramble,James",
    "Drost,Marcia",
    "Foias,Ciprian",
    "Geller,Sue",
    "Hartfiel,Joe",
    "Hensley,Doug",
    "Hobbs,Arthur",
    "Kiffe,Tom",
    "Lewis,Dan",
    "Lowe,Bruce",
    "Maxson,Carl",
    "Mogilevsky,Mila",
    "Pearcy,Carl",
    "Pilant,Michael",
    "Pitts,Jon",
    "Rahe,Maurice",
    "Scarborough,Sherry",
    "Schielack,Janie",
    "Smith,Kirby",
    "Stecher,Mike",
    "Tretkoff,Paula",
    "Vogel,Tom",
    "Walton,Jay",
]
# Professor.create!({firstName:'',lastName:''})
#
#   professors.each do |professor|
#     firstName = professor.split(',')[1]
#     lastName = professor.split(',')[0]
#     Professor.create!({firstName:firstName,lastName:lastName})
#   end

